services:
  frontend:
    container_name: weatherapp-frontend
    build: frontend/
    ports:
      - "3000:3000"
  backend:
    container_name: weatherapp-backend
    build: backend/
    command: npm run start
    ports:
      - "9000:9000"
    volumes:
      - backend:/usr/src/app/src/src
volumes:
    backend: